window.PROJECTS = [
  {
    slug: "project-1",
    number: 1,
    title: "Python OCR Tool for Converting Inspection Sketches into CAD/GIS Linework",
    thumb: "assets/images/ocr_code_web.jpg",
    images: ["assets/images/sewer_connection_uploads_web.jpg", "assets/images/ocr_code_web.jpg", "assets/images/sewer_connection_map_web.jpg", "assets/images/PyConvert2(1)_web.jpg", "assets/images/sewer_service_sketches_web.jpg", "assets/images/PyConvert1(1)_web.jpg"],
    previewLabel: "Preview Blurb",
    preview: "Wrote a Python OCR and vector-conversion tool that read scanned utility inspection forms, extracted addresses and pipe attributes, converted hand sketches into CAD/GIS linework, georeferenced the output, and reduced initial drafting time by about 50%.",
    skillsLabel: "Key Skills Used",
    skills: "Python, pytesseract OCR, image-to-vector conversion, AutoCAD drafting, ArcGIS, georeferencing, scale correction, attribute mapping, debugging, time studies",
    contextLabel: "What / Context",
    context: "During my co-op, I worked with a large set of scanned utility inspection forms that included hand-drawn sketches. These forms captured addresses, pipe size/material, field measurements, and dimensional ties to landmarks like manholes, poles, and nearby structures. The sketches were important for long-term recordkeeping and for contractor reference, but they weren’t consistent enough to use as reliable drafting starting points. I was initially asked to redraw the sketches in AutoCAD so they could be used more easily, but with the number of files, it was clear the manual approach would be slow and repetitive.",
    howLabel: "How / Tools",
    how: "I wrote a Python program that opened each scanned inspection file, used pytesseract OCR to read the address and checklist information, and converted the hand-drawn sketch into CAD/GIS vector linework. The program extracted pipe size, pipe material, address, inspection notes, and other checklist data, then attached those values to the converted geometry as attributes or comments. The address mattered because the code used it to locate the inspection on the map. The program placed the output in the correct CAD/GIS coordinate system, then scaled and rotated the sketch based on existing street and house geometry already drafted in CAD. This turned the sketch from a scanned image into aligned vector geometry that could be used directly in CAD and GIS.",
    resultsLabel: "Results / Outcomes",
    results: "The output was a set of scaled and georeferenced CAD/GIS sketches with inspection information attached. I tested the workflow on dozens of files and produced organized drawings that could be used as drafting starting points or shared externally when needed. Staff no longer had to start from a scanned sketch or redraw every line from scratch. I completed a before-and-after time study and found that the tool reduced initial drafting time by about 50%. This also showed me the inspection workflow itself could be improved further, which led to a separate ArcGIS-based process for collecting the same field information digitally."
  },

  {
    slug: "project-2",
    number: 2,
    title: "Digitization of an inspection workflow through ArcGIS, replacing paper forms.",
    thumb: "assets/images/survey123_form_design_web.jpg",
    images: ["assets/images/survey123_checklist_web.jpg", "assets/images/PyConvert3_web.jpg", "assets/images/survey123_sewer_ties_web.jpg"],
    previewLabel: "Preview Blurb",
    preview: "Built a phone/tablet inspection workflow in ArcGIS Survey123 and Field Maps so inspectors could complete checklists, draw mapped utility vectors, attach photos, collect signatures, work offline, and export finished inspection PDFs automatically.",
    skillsLabel: "Key Skills Used",
    skills: "ArcGIS Survey123, ArcGIS Field Maps, ArcGIS Online, ESRI workflows, mobile forms, field data collection, attribute tables, contractor inspections, network organization",
    contextLabel: "What / Context",
    context: "During my co-op, inspections were being documented through paper forms for multiple inspection types. Each form included checklist items, inspector name/date, address, utility details like pipe size/material, field measurements, photos, a contractor signature, and a sketch showing dimension ties to fixed landmarks. The paper process worked, but it created extra steps: manual completion, scanning, renaming, filing, and then reinterpreting the scanned record later. The sketch quality also depended on the person, so the final record wasn’t always consistent.",
    howLabel: "How / Tools",
    how: "I built a digital inspection workflow using ArcGIS Survey123, ArcGIS Field Maps, ArcGIS Online, and ESRI tools. I created a mobile form with the same checklist items from the paper form, plus fields for inspector name, date, address, utility information, photo uploads, and contractor signatures. In Field Maps, I set up the map workflow so inspectors could zoom into the work area, draw utility vectors directly on the map, and add attributes such as pipe size, pipe material, dimensional ties, and nearby reference points. I also set up offline use so the form could be completed in low-signal areas and uploaded automatically once the phone or tablet reconnected to Wi-Fi. After submission, the inspection data appeared in ESRI and could be exported as a PDF matching the original paper form format.",
    resultsLabel: "Results / Outcomes",
    results: "The system replaced the paper process for the inspection types I digitized. Inspectors could complete the checklist, draw mapped utility geometry, attach photos, collect signatures, and generate the final inspection PDF without scanning paper forms. I first built the workflow for utility inspections, then expanded it to drain and water inspections. I also installed and configured the forms on staff phones so the office could use the system in the field. The process improved record consistency, connected field information directly to GIS, reduced manual file handling, and made it easier for future staff to find and understand inspection records."
  },

  {
    slug: "project-3",
    number: 3,
    title: "Detention Pond Redesign from Field Survey & CAD modeling to Construction Planning",
    thumb: "assets/images/RDF 1(1)_web.jpg",
    images: ["assets/images/RDF 1(1)_web.jpg", "assets/images/RDF 2(1)_web.jpg", "assets/images/rdf survey_web.mp4"],
    previewLabel: "Preview Blurb",
    preview: "Collected 500+ total station survey points, built a 3D CAD surface model, created three detention pond redesign options, and supported the final plan set, specifications, bid calculations, and construction planning for a failing stormwater basin.",
    skillsLabel: "Key Skills Used",
    skills: "Total station surveying, AutoCAD, 3D surface modeling, contours, datum conversion, pipe networks, plan/profile drawings, details, specifications, bid tabulation, redline revisions.",
    contextLabel: "What / Context",
    context: "During my co-op, I worked on a detention pond redesign next to a recycling center where several drainage networks discharged into the basin. The pond wasn’t performing the way it needed to, so the goal was to improve infiltration and overall function while also making the design clear enough to move into construction planning. I reviewed the site in dry conditions, then came back during rain to understand how water entered and sat in the basin so the redesign could be based on what was actually happening in the field.",
    howLabel: "How / Tools",
    how: "I helped complete the topographic survey over about three days and operated the total station to capture 500+ points in the field. I collected elevations and coordinates across the top of slope, side slopes, basin bottom, surrounding pavement, edge of pavement, start of roadway, catch basins, poles, trees, utilities, water limits, and other existing site features. I uploaded the survey data into CAD, converted the elevations to the correct datum, built a 3D surface model, and interpolated between points to create major and minor contour lines. I then created the drawing package with a title sheet, contract number, site image, existing conditions sheet, and three redesign options. The first option used a snake-shaped basin to increase the water travel path and give stormwater more time to infiltrate. The second option used three lowered basin areas separated by raised berms so trash would be slowed or trapped while water could still pass through and seep into the ground. The third option kept the existing layout mostly intact as a lower-cost construction option. I also created side profiles, utility pipe network drawings, drain/sewer/water information, catch basin details, outfall details, installation details, and presentation graphics with CAD hatching, grass, shrubs, trees, and water.",
    resultsLabel: "Results / Outcomes",
    results: "The final drawing package included the surveyed CAD base, 3D surface, contour plan, existing conditions plan, three proposed design plans, side profiles, utility/pipe network layouts, construction details, specifications, bid calculations, and bid tabulation comparing contractor costs. My supervisor redlined the drawings multiple times, and I revised the package after each review. The second design with the three lowered basin areas and raised berms moved into construction planning. The project turned a field issue into a documented, reviewable set of design options supported by survey data, grading information, and clear plan production."
  },

  {
    slug: "project-4",
    number: 4,
    title: "Robotic Rover for Pipe Inspection and New Pipe Repair Design",
    thumb: "assets/images/eaton(2)_web.jpg",
    images: ["assets/images/pipe_inspection_web.jpg", "assets/images/web_image_set4_4.jpg", "assets/images/eaton_court_plan_profile_web.jpg", "assets/images/Eaton Court_web.jpg", "assets/images/eaton court pipes_web.mp4"], 
    previewLabel: "Preview Blurb",
    preview: "Reviewed robotic crawler sensor data from a damaged drainage pipe, identified the concavity causing blockage and downstream overflow, mapped the surrounding utilities in AutoCAD, and helped design a new manhole installation that fixed the pipe and improved drainage flow.",
    skillsLabel: "Key Skills Used",
    skills: "AutoCAD, robotic crawler inspection, inspection data analysis, existing conditions drafting, utility coordination, design, plan set production, cost-aware design, field verification",
    contextLabel: "What / Context",
    context: "During my co-op, I worked on a drainage repair where a pipe had a major concavity and damage that allowed soil to enter and create a blockage. There was also a downstream structure experiencing overflow, so the issue was affecting system performance beyond a single location. The goal was to identify what was failing, confirm it using inspection data, and support a repair approach that addressed the root problem without overcomplicating the fix.",
    howLabel: "How / Tools",
    how: "The pipe was inspected using a remote-controlled robotic crawler rover. The rover traveled through the inside of the pipe and collected data using a camera, lights, night vision, thermal sensor, motion sensors, and other inspection sensors. I reviewed the footage and sensor data to locate the damaged section, confirm the concavity, and understand how the blockage was affecting flow. In AutoCAD, I mapped the pipe, outlets, and surrounding utilities using utility records and a georeferenced CAD base. I brought in nearby sewer, water, drain, gas, electric, manholes, and other existing conditions so the repair could be designed around the full utility layout. I considered patch work as one option, then developed the new manhole installation option as a practical way to access the damaged area and improve system performance at a reasonable cost.",
    resultsLabel: "Results / Outcomes",
    results: "The selected repair was the new manhole installation. I helped produce the CAD design information used to support construction. After the repair, I reviewed follow-up inspection footage from the robotic crawler to confirm the damaged section had been addressed and that overflow was no longer occurring at the downstream structure. The work improved drainage behavior along the street and used inspection data to verify the outcome. The utility mapping work also supported later design tasks by strengthening the office’s CAD base for existing conditions."
  },

  {
    slug: "project-5",
    number: 5,
    title: "Town-Wide CAD Drawing of Utilities, Orthoimagery, and Contour Base Map System",
    thumb: "assets/images/town_utilities_civil3d_web.jpg",
    images: ["assets/images/town_utilities_civil3d_web.jpg", "assets/images/contour_surface_web.jpg", "assets/images/town utilies 2_web.mp4"],
    previewLabel: "Preview Blurb",
    preview: "Created a reusable town-wide CAD base by converting GIS utility data, 2025 MassDOT orthophotography, and drone-derived elevation contours into georeferenced drafting files used by the engineering office to start plan sets faster.",
    skillsLabel: "Key Skills Used",
    skills: "AutoCAD, Civil 3D, ArcGIS, GIS-to-CAD conversion, georeferencing, CAD blocks, CAD points, MassDOT standards, contour generation, elevation interpolation, coordinate systems.",
    contextLabel: "What / Context",
    context: "During my co-op, a lot of projects started with the same setup work: bringing in existing utility locations, aerial imagery, and elevation references before any design could begin. Since that setup repeated across many drawings, I built a reusable CAD base system so new plan sets could start from a consistent, georeferenced existing-conditions foundation.",
    howLabel: "How / Tools",
    how: "I built the system in three parts. First, I exported utility data from GIS and brought it into AutoCAD. The CAD file included water lines, drain lines, sewer lines, manholes, catch basins, poles, electric lines, electric manholes, and other utility features. I georeferenced the data to the correct coordinate system and created both block-based and point-based versions so staff could choose the format that matched their drafting style. Second, I created a 2025 orthoimagery resource by taking the MassDOT ortho layer, reducing it to the project area, and exporting overlapping 200 ft by 200 ft georeferenced image tiles so there were no gaps at tile boundaries. Third, I created a contour layer using drone-derived elevation data and interpolated between elevation points to generate a town-wide reference for early design review.",
    resultsLabel: "Results / Outcomes",
    results: "The final files included the CAD utility base, a georeferenced orthoimagery tile set, and a contour layer that could be reused across projects. Engineers began using these files by copying the project area into their drawing instead of rebuilding the same existing-conditions setup each time. This improved drafting consistency, reduced startup time for plan sets, and gave the office a shared, georeferenced foundation for utilities, imagery, and elevation data."
  },

  {
    slug: "project-6",
    number: 6,
    title: "CA Light Designs: Custom LED Sign Business- Designing, Manufacturing, and Selling Custom Products",
    thumb: "assets/images/ca_light_products_web.jpg",
    images: ["assets/images/web_image_set5_1.jpg", "assets/images/web_image_set4_2.jpg", "assets/images/web_image_set4_3.jpg"],
    previewLabel: "Preview Blurb",
    preview: "Founded and operated CA Light Designs, designing custom acrylic LED signs, engraving and assembling each product, modifying the engraving machine for better precision and speed, building the Wix/Etsy/Instagram/TikTok sales system, and doubling order volume through production improvements.",
    skillsLabel: "Key Skills Used",
    skills: "Product design, Silhouette Studio, product assembly, machine optimization, manufacturing, workflow improvement, quality control, Wix, Etsy, customer support, order fulfillment.",
    contextLabel: "What / Context",
    context: "CA Light Designs was a custom-engraved LED sign business that I started in high school and ran myself through senior year. I designed and manufactured personalized acrylic LED signs, mostly for colleges, celebrations, and decorative use. I handled customer communication, design layout, engraving setup, acrylic production, LED assembly, quality checks, packaging, order fulfillment, website updates, and marketing. The design, machine setup, and online sales channels were all part of the same process because each order started with a customer request and ended with a finished product that had to be made cleanly and shipped on time.",
    howLabel: "How / Tools",
    how: "For each order, I worked with the customer to understand the school, logo, name, message, or design style they wanted. I created the layout in CAD-like design software and Silhouette Studio, then adjusted the geometry so the engraving would cut cleanly into acrylic and light evenly in the LED base. I had to control line thickness, spacing, engraving depth, acrylic size, alignment, and how the light would travel through the engraved design. As demand increased, the engraving machine became the production bottleneck. The original metal cutting attachment had a sharp edge, but it was too dull and not strong enough for the material and finish quality I needed. I researched compatible replacement parts, modified the engraving setup, and adjusted the machine speed so it could produce cleaner lines faster. I also built the CA Light Designs website on Wix and created Etsy, Instagram, and TikTok pages to bring in customers, show finished products, and manage sales.",
    resultsLabel: "Results / Outcomes",
    results: "The work produced finished custom LED signs, a repeatable engraving and assembly process, an improved engraving machine setup, a Wix website, an Etsy storefront, and social media sales channels. The machine changes improved engraving quality and reduced production time, which let me complete more orders as demand grew. The business received strong customer feedback and five-star reviews, and the improved production and marketing workflow helped double order volume year over year. The project combined product design, acrylic material behavior, machine setup, tooling changes, manufacturing speed, quality control, customer feedback, and order fulfillment."
  },

  {
    slug: "project-7",
    number: 7,
    title: "Interactive Clean Energy Educational Exhibit with Wind Turbine, House Model, LEDs, and Arduino/MATLAB Game",
    thumb: "assets/images/web_image_set5_4.jpg",
    images: ["assets/images/web_image_set5_4.jpg", "assets/images/web_image_set5_5.jpg", "assets/images/web_image_set5_2.jpg", "assets/images/web_image_set5_6.jpg", "assets/images/web_image_set5_3.jpg"],
    previewLabel: "Preview Blurb",
    preview: "Designed and built an interactive clean energy exhibit with a laser-cut house, SolidWorks-modeled 3D-printed wind turbine, Arduino/MATLAB trivia game, LED feedback, push buttons, iPad visuals, and a chime system for Boston middle school students.",
    skillsLabel: "Key Skills Used",
    skills: "SolidWorks, AutoCAD, MATLAB, Arduino, 3D printing, Fusion 360, laser cutting, LED wiring, circuits, woodworking, design, prototyping, and user-focused design.",
    contextLabel: "What / Context",
    context: "In Cornerstone of Engineering at Northeastern, my group and I built an interactive clean energy exhibit for an end-of-semester exposition where Boston middle school students came to campus. The goal was to teach clean energy through a physical model and interactive game. We wanted students to see wind energy turn into a visible output, answer questions, and receive immediate feedback from the system.",
    howLabel: "How / Tools",
    how: "I helped design the exhibit layout in AutoCAD and worked on the physical build using wood, circuits, 3D-printed components, and laser-cut parts. We laser cut a house model and placed LEDs throughout it. We modeled the wind turbine in SolidWorks and 3D printed it so students could spin it. When the turbine spun, LEDs on the house lit up to show how wind energy can power a load. We also created a MATLAB/Arduino trivia game connected to an iPad. The iPad displayed a welcome screen, a short clean energy video, and about eight true-or-false questions. Students answered with a green button for true and a red button for false. Correct answers triggered lights and a chime. The exhibit also included wiring space, buttons, labels, and support structure so the system could be used repeatedly during the event.",
    resultsLabel: "Results / Outcomes",
    results: "The final exhibit included the laser-cut house, SolidWorks turbine model, 3D-printed turbine, LED lighting system, push-button controls, Arduino/MATLAB game, iPad visuals, and chime feedback. During the exposition, the code ran without glitches and the physical parts stayed intact during repeated student use. Students answered the questions, spun the turbine, saw the lights respond, and connected the turbine motion to clean energy output. The project received strong feedback from students, teachers, peers, and instructors."
  },

  {
    slug: "project-8",
    number: 8,
    title: "Northeastern University Mechanical Engineering Laboratory Work & Modeling",
    thumb: "assets/images/manufacturing_lab_web.jpg",
    images: ["assets/images/manufacturing_lab_web.jpg"],
    previewLabel: "Preview Blurb",
    preview: "Completed Northeastern mechanical engineering labs covering Instron testing, impact and hardness testing, microscopy and XRD materials analysis, torsional vibration and mechanism kinematics experiments, and sensor-based data collection with MATLAB and Arduino.",
    note: "(a through d below should all be within the same project button, just make them different tiles on the same page)",
    subsections: [
      {
        title: "a. Instron Mechanical Testing and MATLAB Stress-Strain Analysis",
        thumb: "assets/images/lab_equipment_1_web.jpg",
        images: ["assets/images/lab_equipment_1_web.jpg", "assets/images/lab_equipment_2_web.jpg"],
        previewLabel: "Preview Blurb",
        preview: "Used Instron testing systems, Bluehill software, and MATLAB to run tensile, bending, compression, torsion, and buckling tests, then calculated material properties from load, displacement, torque, and strain data.",
        skillsLabel: "Key Skills Used",
        skills: "Instron MicroTorsion, Bluehill, MATLAB, tensile testing, bending testing, compression testing, torsion testing, buckling testing, stress-strain curves, failure analysis.",
        contextLabel: "What / Context",
        context: "In Intro to Materials Science and Mechanics of Materials at Northeastern, I completed several labs studying how materials respond to load. The labs covered tension, bending, compression, torsion, buckling, elastic deformation, plastic deformation, yield, ultimate strength, and fracture. The goal was to take the equations from class and connect them to data collected from testing machines.",
        howLabel: "How / Tools",
        how: "I used the Instron 5582 for tensile and bending tests and the Instron MicroTorsion system for torsional testing. I used Bluehill software to configure the tests, control the machines, record data, and export results. I also worked with compression and buckling setups to study how different samples failed under axial load. After collecting the data, I used MATLAB to plot stress-strain curves, identify the elastic region, calculate Young’s modulus from the slope, locate yield behavior, find ultimate tensile strength, and compare failure behavior between materials. For torsion, I used torque and angular deformation data to analyze shear response and calculate shear modulus.",
        resultsLabel: "Results / Outcomes",
        results: "The work produced lab reports, stress-strain graphs, material property calculations, and failure analysis. I calculated Young’s modulus, yield strength, ultimate tensile strength, shear modulus, and other values depending on the test. I also compared how different loading modes changed failure behavior. These labs gave me direct experience setting up mechanical tests, using Instron and Bluehill systems, processing test data in MATLAB, and turning raw machine data into engineering conclusions."
      },
      {
        title: "b. Impact, Hardness, Microstructure, Stress Concentration, and XRD Materials Analysis",
        thumb: "assets/images/toughness_testing_diagram_web.jpg",
        images: ["assets/images/toughness_testing_diagram_web.jpg", "assets/images/charpy_impact_tester_web.jpg"],
        previewLabel: "Preview Blurb",
        preview: "Measured fracture energy, Rockwell hardness, microstructure, stress concentrations, polymer crystal growth, Charpy impact testing, optical/polarized microscopy, XRD.",
        skillsLabel: "Key Skills Used",
        skills: "Charpy impact testing, Fracta software, liquid nitrogen testing, furnace heating, Rockwell hardness tester, optical microscopy, polished and etched samples, polarized optical microscope, polariscope, WAXD-RAPID2 XRD, Archimedes density method, fracture energy, phase percentage measurement, and material identification.",
        contextLabel: "What / Context",
        context: "In my materials labs, I studied how material behavior changes with temperature, hardness, internal structure, stress concentration, polymer crystal growth, and crystal structure. These tests helped explain why materials fail differently even when they are placed under similar loads. The focus was on connecting the material’s internal structure and test conditions to its mechanical behavior.",
        howLabel: "How / Tools",
        how: "I used an Instron Charpy Impact Tester with Fracta software to measure fracture energy under sudden loading. I tested samples after liquid nitrogen cooling and furnace heating to compare toughness at different temperatures. I used a digital Rockwell hardness tester to compare metal hardness values and relate hardness to strength. For microstructure work, I used optical microscopes to examine polished and etched metal samples and estimate phase percentages in alloys. I used a polarized optical microscope to observe polymer crystal growth and a polariscope to see stress concentrations in plastic parts. I also used a WAXD-RAPID2 X-ray diffractometer and Archimedes density measurements to help identify crystal structure.",
        resultsLabel: "Results / Outcomes",
        results: "The work produced fracture energy data, hardness values, microscope observations, phase percentage estimates, crystal-growth observations, stress concentration images, XRD results, density measurements, and written analysis. The tests showed how temperature affects impact toughness, how hardness relates to strength, how microstructure changes material behavior, and how stress concentrations appear in transparent plastic parts. The XRD and density work connected measured material data to crystal structure identification."
      },
      {
        title: "c. Torsional Vibration and Whitworth Quick Return Motion Testing",
        thumb: "assets/images/lab_equipment_4_web.jpg",
        images: ["assets/images/lab_equipment_4_web.jpg", "assets/images/lab_equipment_3_web.jpg"],
        previewLabel: "Preview Blurb",
        preview: "Tested mechanical motion and vibration systems using an ECP torsional vibration system, Whitworth Quick Return mechanism, ultrasonic sensor, laser tachometer, Python, and MATLAB to compare measured motion with analytical models.",
        skillsLabel: "Key Skills Used",
        skills: "Torsional Vibration System, Whitworth Quick Return Apparatus, Go!Motion ultrasonic sensor, laser tachometer, Python, MATLAB, damping, kinematics, RPM testing, error analysis.",
        contextLabel: "What / Context",
        context: "In Dynamics and Vibrations, I completed labs comparing analytical mechanical models with measured data. One lab studied viscous damping in a torsional vibration system with different mass center-distance settings, including 9 cm and 4 cm. Another lab studied the position, velocity, and acceleration of a modified Whitworth Quick Return mechanism at 40, 60, and 80 RPM. Both labs showed how friction, alignment, sensor setup, and energy losses affect the difference between theoretical and measured motion.",
        howLabel: "How / Tools",
        how: "For the torsional vibration lab, I used the ECP Model 205a Torsional Vibration System and its software to record amplitude counts as the system oscillated and decayed. I used the measured decay to calculate experimental damping coefficients and compared them to theoretical values. For the Whitworth Quick Return lab, I used the mechanism, a Go!Motion ultrasonic distance sensor, a non-contact laser tachometer, and Python/MATLAB calculation models. I measured slider position, compared it to rigid-body kinematic equations, and analyzed position, velocity, and acceleration at different RPM settings.",
        resultsLabel: "Results / Outcomes",
        results: "In the torsional vibration lab, the experimental damping coefficients were consistently higher than the theoretical values. One result was about 0.111 rad/s compared with a theoretical value of 0.05 rad/s. The difference was likely caused by measurement error, slight mass positioning error, and energy loss from the initial angular pulse. In the Whitworth Quick Return lab, the data confirmed asymmetric slider motion: the forward stroke was slower and the return stroke was faster. The measured peak-to-peak motion was smaller than the theoretical prediction, likely because of friction, sensor baseline shifts, and alignment offsets. The final work included plots, calculations, comparison tables, and written error analysis."
      },
      {
        title: "d. Sensor Measurement, Thermal Data Collection, and Uncertainty Analysis",
        thumb: "assets/images/rtd_thermocouple_web.jpg",
        images: ["assets/images/rtd_thermocouple_web.jpg", "assets/images/lux_meter_web.jpg"],
        previewLabel: "Preview Blurb",
        preview: "Collected and analyzed measurement data using calipers, micrometers, temperature sensors, RTDs, thermocouples, lux sensors, Arduino, MATLAB, and uncertainty analysis to study measurement accuracy and environmental variation.",
        skillsLabel: "Key Skills Used",
        skills: "Arduino, MATLAB, RTDs, thermocouples, lux sensors, calipers, micrometers, uncertainty analysis, sensor placement, data plotting, and measurement error analysis.",
        contextLabel: "What / Context",
        context: "In Measurement and Analysis with Thermal Applications and physics labs, I studied how measurement setup affects data quality. These labs covered precision, random error, systematic error, temperature distribution, lighting uniformity, sensor placement, and uncertainty. The goal was to understand what the measured value meant, what could have affected it, and how much confidence should be placed in the result.",
        howLabel: "How / Tools",
        how: "In one uncertainty lab, I used calipers and micrometers to measure a solid cylinder and a metallic thread, then calculated volume and area while comparing random and systematic error. In thermal and measurement labs, I used Arduino-based setups with temperature sensors, RTDs, and thermocouples, then processed readings in MATLAB. In a smartphone sensor lab, I used an iPhone 14 ambient light sensor with the Physics Toolbox app to measure light levels at four coordinates on a study desk. In a classroom temperature uniformity project, I collected temperature data in Richards, Dodge, and Ryder halls under normal conditions and disturbed HVAC conditions, including open doors or windows.",
        resultsLabel: "Results / Outcomes",
        results: "The uncertainty lab showed that precise tools like micrometers reduce scale error, but systematic and random error still affect final calculations. The smartphone sensor lab found an average illumination of 6302.5 lux, with readings ranging from 7568.2 lux to 3912.0 lux, showing that the desk was bright but unevenly lit. The classroom temperature project produced mean temperatures and temperature ranges near windows, doors, vents, and center locations to evaluate comfort and HVAC effects. The final work included plots, calculations, tables, and written analysis based on measured data."
      }
    ]
  },

  {
    slug: "project-9",
    number: 9,
    title: "Formula-Style Electric Race Car Tire & Inertia Analysis",
    thumb: "assets/images/web_image_set4_5.jpg",
    images: ["assets/images/web_image_set4_5.jpg", "assets/images/RacingClubLogo_web.jpg"],
    previewLabel: "Preview Blurb",
    preview: "Supported NU Electric Racing’s tire optimization work by evaluating tire material choices, mass distribution, rotational inertia, and MATLAB plots used to study acceleration and efficiency tradeoffs in a Formula-style electric race car.",
    skillsLabel: "Key Skills Used",
    skills: "Rotational inertia analysis, tire material evaluation, MATLAB plotting, dynamics, acceleration efficiency, wheel/tire mass distribution, team-based design, Formula-style race car development.",
    contextLabel: "What / Context",
    context: "NU Electric Racing is Northeastern’s student team that designs and builds a Formula-style electric race car to compete against other schools. I volunteered on the tire optimization section. The focus was on how tire selection affects the full vehicle, especially acceleration and efficiency. Since tires rotate, their mass and radius directly affect rotational inertia. A heavier tire or a tire with more mass farther from the center requires more energy to accelerate, which can slow the car down.",
    howLabel: "How / Tools",
    how: "I worked with the group to evaluate tire material choices, mass distribution, rotational inertia, and performance tradeoffs. We looked at how tire mass and geometry affect the energy required to spin the wheel and how that connects to acceleration. I helped with group modules used to analyze data and create MATLAB graphs and plots. The work connected dynamics concepts to the car system, including mass moment of inertia, angular acceleration, tire material, traction needs, and the tradeoff between reducing tire inertia and keeping enough grip and durability for racing.",
    resultsLabel: "Results / Outcomes",
    results: "The work produced group calculations, MATLAB plots, and data-based comparisons used in tire selection and optimization discussions. The analysis helped the tire section compare how different tire choices could affect rotational inertia, acceleration, and efficiency. The project gave me experience working on a vehicle subsystem where a single component choice affects the performance of the full car."
  },

  {
    slug: "project-10",
    number: 10,
    title: "SolidWorks Prosthetic Hand Mechanism Design",
    thumb: "assets/images/prosthetic_hand_sketch_web.jpg",
    images: ["assets/images/HandClubLogo_web.jpg", "assets/images/prosthetic_hand_sketch_web.jpg"],
    previewLabel: "Preview Blurb",
    preview: "Worked on NU Give a Hand’s prosthetic hand section by modeling hand mechanisms in SolidWorks and improving part geometry, finger motion, assembly fit, and 3D-printable design features.",
    skillsLabel: "Key Skills Used",
    skills: "SolidWorks, prosthetic hand design, mechanism modeling, 3D printing, linkage geometry, assembly design, design iteration, human-centered design, and prototype refinement.",
    contextLabel: "What / Context",
    context: "NU Give a Hand is a Northeastern club where students design and build prosthetic hands for people in need. I worked on the hand section, which focused on the CAD model and mechanical mechanisms of the prosthetic hand. The design needed to be functional, lightweight, printable, durable, and simple enough to assemble.",
    howLabel: "How / Tools",
    how: "I worked directly in SolidWorks on the hand model and mechanism layout. I focused on how the parts fit together, how the fingers moved, and how geometry changes affected grip motion. I reviewed linkage movement, part clearance, print orientation, material use, and assembly constraints. The main design challenge was translating motion into useful finger movement while keeping the parts simple enough to print and assemble.",
    resultsLabel: "Results / Outcomes",
    results: "The work produced SolidWorks models and design improvements to the prosthetic hand mechanism. The changes focused on improving the geometry, motion, and manufacturability of the hand components. The project gave me experience with CAD assemblies, mechanism design, 3D-printable components, and design decisions where comfort, function, assembly, and durability all matter."
  },

  {
    slug: "project-11",
    number: 11,
    title: "Intersection Safety Redesign with Signaling Redesign",
    thumb: "assets/images/great plain 2_web.jpg",
    images: ["assets/images/great plain 2_web.jpg", "assets/images/great_plain_intersection_web.jpg", "assets/images/great plain 1(1)_web.jpg"],
    previewLabel: "Preview Blurb",
    preview: "Created CAD graphics for a problematic intersection by using root-cause analysis to study accident patterns, then developed redesign concepts with added lanes, left-turn lanes, and signal changes.",
    skillsLabel: "Key Skills Used",
    skills: "AutoCAD, intersection layout, lane geometry, traffic signal concept design, Five Whys, Six Sigma-style root cause analysis, existing conditions review, safety-focused design, and presentation graphics.",
    contextLabel: "What / Context",
    context: "During my co-op, I worked on concept graphics for an intersection that had repeated traffic problems and safety concerns. The goal was to break down why the conflicts were happening and create clear redesign options that improved driver flow and reduced conflict points.",
    howLabel: "How / Tools",
    how: "I used root-cause methods such as Five Whys and a structured problem breakdown to think through turning conflicts, lack of left-turn space, unclear lane use, signal placement, driver decision points, and the existing intersection geometry. I then used AutoCAD to create design graphics showing added lanes, dedicated left-turn lanes, and signal changes. I focused on making each option clear enough to compare how geometry and signal changes would affect traffic movement.",
    resultsLabel: "Results / Outcomes",
    results: "The work produced CAD-based redesign graphics showing multiple improvement concepts. One option moved forward into the next phase. The project turned a real safety problem into clear design choices that could be reviewed, compared, and used for decision-making."
  },
  
  {
    slug: "project-12",
    number: 12,
    title: "Python Program with OCR for File Organization and Search Index",
    thumb: "assets/images/ocr_organize_code_web.jpg",
    images: ["assets/images/ocr_organize_code_web.jpg", "assets/images/ocr_organize_code_web.jpg"],
    previewLabel: "Preview Blurb",
    preview: "Wrote a Python OCR script that processed thousands of scanned project files, extracted addresses and project names, renamed the files, organized them into a searchable folder hub, and reduced coworker lookup time by 75%.",
    skillsLabel: "Key Skills Used",
    skills: "Python, pytesseract OCR, scanned PDF processing, file renaming automation, folder structure design, project indexing, metadata extraction, debugging, and time study analysis.",
    contextLabel: "What / Context",
    context: "During my co-op, I worked with a large archive of scanned project files where naming and folder organization weren’t consistent across years. That made it harder to find older records quickly when someone needed them for design background or research. The goal was to make the archive searchable and predictable so someone could locate a file without opening dozens of PDFs.",
    howLabel: "How / Tools",
    how: "I wrote a Python script using pytesseract OCR to read scanned PDFs and extract identifiers such as project address, project location, and project name. Based on that text, the script renamed each file, moved it into a structured folder hub, and created an index showing where files could be found. I wrote the first version in about a day and ran it across thousands of documents in batch.",
    resultsLabel: "Results / Outcomes",
    results: "The script organized thousands of files in minutes, producing renamed documents, structured folders, and a searchable index staff could use for faster lookup. I completed a before-and-after time study and found file lookup time decreased by 75%. The result was a much faster way to find archive records and less time spent searching through scans."
  },

  {
    slug: "project-13",
    number: 13,
    title: "Construction Time-Lapse Documentation for Field Projects",
    thumb: "assets/images/Timelapse_web.jpg",
    images: ["assets/images/usts_web.mp4", "assets/images/tennis_web.mp4"],
    previewLabel: "Preview Blurb",
    preview: "Created multi-month construction time-lapse videos for Town of Wellesley projects, including a gas pump station redesign and tennis court redesign, to document field progress from start to finish.",
    skillsLabel: "Key Skills Used",
    skills: "Construction documentation, field progress tracking, video editing, iMovie, Clipchamp, project sequencing, visual communication, and design-to-construction documentation.",
    contextLabel: "What / Context",
    context: "At Wellesley, I created time-lapse videos for construction projects around town, including projects I helped design. Two examples were a gas pump station redesign and a tennis court redesign, each documented over about four months. The goal was to record how each project changed over time and show the sequence from early construction through final conditions.",
    howLabel: "How / Tools",
    how: "I recorded and organized footage from the sites over multiple months, then edited the clips using iMovie and Clipchamp. I selected footage that showed major project stages, including site preparation, equipment movement, construction progress, installation work, and final conditions. I arranged the clips in order so the final videos showed the project timeline clearly.",
    resultsLabel: "Results / Outcomes",
    results: "The final videos condensed months of construction into clear visual summaries. They showed the project sequence, made field progress easier to communicate, and created a record of how the work was built. The videos also helped connect the design and plan set stage to the field construction stage."
  },

  {
    slug: "project-14",
    number: 14,
    title: "Coding With a Cause: Website Design Outreach Program for Middle School Students",
    thumb: "assets/images/web_image_set4_6.jpg",
    images: ["assets/images/web_image_set4_6.jpg", "assets/images/web_image_set4_7.jpg"],
    previewLabel: "Preview Blurb",
    preview: "Led a high school computer science outreach program that taught middle school students coding and website design, expanded from one school to three, and ended with students presenting their own websites.",
    skillsLabel: "Key Skills Used",
    skills: "Lesson planning, presentation design, outreach coordination, Scratch, Wix, basic web design, coding instruction, event planning, team leadership, and technical communication.",
    contextLabel: "What / Context",
    context: "From September 2022 to June 2023, I served as President of Coding With a Cause, the computer science club at my high school. I was in charge of planning outreach events where club members taught middle school students basic coding and website design. The goal was to make coding understandable for younger students and give them a project they could build and show.",
    howLabel: "How / Tools",
    how: "My co-president and I planned monthly outreach events, created presentations, wrote lesson plans, and organized activities. We used beginner-friendly tools such as Scratch and Wix so students could learn coding logic, design structure, and website layout without needing advanced programming knowledge. I focused the outreach around website building because it let students create something personal and visual by the end of the program.",
    resultsLabel: "Results / Outcomes",
    results: "The program started with one middle school and expanded to three more because the first sessions went well. Attendance grew over time, and by the end of the year, students had built their own websites showing their designs, creativity, and coding knowledge. The work produced lesson plans, presentations, outreach sessions, and student-created websites."
  }
];
